### ISSUE TITLE
github.com/can3p/bunny

### ISSUE THREAD

**Issue by gedw99** [can3p/gogo-cli#3]
does not exist, but you reference it in the README example

Maybe Pcom is better ?

**Comment by can3p** [comment]
Hey, `bunny` is just an example name, not e real service. One thing is correct - it probably makes sense to have a separate repo with a generated code, which everyone can clone to see the result. It's not `pcom` though, I'll create a separate test repo for that

**Comment by gedw99** [comment]
Ok makes sense.

Can then work up the demo repo
